// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc100.Robot2013;
    
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static final Encoder climberEncoder = new Encoder(5,6);
    public static final DigitalInput climberTopSwitch = new DigitalInput(7);
    public static final DigitalInput climberBottomSwitch = new DigitalInput(8);
    public static final DigitalInput climberPoleSwitch = new DigitalInput(9);  
    
    public static final AnalogChannel climberRightFixedIR = new AnalogChannel(4);
    public static final AnalogChannel climberLeftFixedIR = new AnalogChannel(5);
    public static final AnalogChannel climberRightMovingIR = new AnalogChannel(6);
    public static final AnalogChannel climberLeftMovingIR = new AnalogChannel(7);
    public static final Victor climberTopMotor = new Victor(3);
    public static final Victor climberBottomMotor = new Victor(4);
    
    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        
        LiveWindow.addSensor("Climber", "ClimberEncoder" , climberEncoder);
        
    }
}