// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc100.Robot2013.subsystems;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
import org.usfirst.frc100.Robot2013.RobotMap;
/**
 *
 */
public class Climber extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    Encoder climberEncoder = RobotMap.climberClimberEncoder;
    SpeedController climberMotor = RobotMap.climberClimberMotor;
    DigitalInput topClimberSwitch = RobotMap.climberTopClimberSwitch;
    DigitalInput bottomClimberSwitch = RobotMap.climberBottomClimberSwitch;
    DigitalInput rightFixedHookMetalSensor = RobotMap.climberRightFixedHookMetalSensor;
    DigitalInput leftFixedHookMetalSensor = RobotMap.climberLeftFixedHookMetalSensor;
    DigitalInput rightMovingHookMetalSensor = RobotMap.climberRightMovingHookMetalSensor;
    DigitalInput leftMovingHookMetalSensor = RobotMap.climberLeftMovingHookMetalSensor;
    DigitalInput poleLimitSwitch = RobotMap.climberPoleLimitSwitch;
    Solenoid emergencyBrake = RobotMap.climberEmergencyBrake;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    int level=0;//level of the pyramid that the robot is at
    
    //Make these preferences!
    boolean homeUp=true;//automatically home elevator to top or bottom
    double elevatorSpeed=1;//speed that elevator will move
    double homingSpeed=.2;//speed for homingSequence method
    private double homingReverseSpeed=.1;//not very fast
    private int encoderMax=5000;//highest point elevator should reach
    private int encoderMin=0;//lowest point elevator should reach
    private int errorLowerLimit=50;//limit for how far the hook moves without catching before it's considered an error and tries again
    private int errorUpperLimit=50;//errorUpperLimit is used in the lowerElevator method, errorLowerLimit is used in the raiseElevator method
    private int lowerElevatorPartwayLimit;//how far the robot has to pull itself up the third time
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    
    //empty
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    //sets climber speed to given value
    public void manualControl(double d){
        climberMotor.set(0);
        if (topClimberSwitch.get()&&d<0){
            climberMotor.set(d);
        }
        if (bottomClimberSwitch.get()&&d>0){
            climberMotor.set(d);
        }
        if(!topClimberSwitch.get()&&!bottomClimberSwitch.get()){
            climberMotor.set(d);
        }
    }
    
    //raises the elevator, tries again if hooks don't catch
    public void raiseElevator(){
        if (!getUpperLimit()){
            if (!getError(true)||climberEncoder.get()<errorLowerLimit){
                climberMotor.set(elevatorSpeed);
            }
            else {
                if (!getLowerLimit()){
                    climberMotor.set(-elevatorSpeed);
                }
            }
        }
        else {
            climberMotor.set(0);
        }
    }
    
    //lowers the elevator, tries again if hooks don't catch
    public void lowerElevator(){
        if (!getLowerLimit()){
            if (!getError(false)||climberEncoder.get()>errorUpperLimit){
                climberMotor.set(-elevatorSpeed);
            }
            else {
                if (!getUpperLimit()){
                    climberMotor.set(elevatorSpeed);
                }
            }
        }
        else {
            climberMotor.set(0);
        }
    }
    
    //lowers elevator partway for last pull-up at end
    public void lowerElevatorPartway(){
        if (climberEncoder.get()>lowerElevatorPartwayLimit){
            if (!getError(false)||climberEncoder.get()>errorUpperLimit){
                climberMotor.set(-elevatorSpeed);
            }
            else {
                if (!getUpperLimit()){
                    climberMotor.set(elevatorSpeed);
                }
            }
        }
        else {
            climberMotor.set(0);
        }
    }
    
    //whether the elevator has reached the bottom
    public boolean getLowerLimit(){
        return bottomClimberSwitch.get()||climberEncoder.get()<encoderMin;
    }
    
    //whether the elevator has reached the top
    public boolean getUpperLimit(){
        return topClimberSwitch.get()||climberEncoder.get()>encoderMax;
    }
    
    //called when robot goes up a level of the pyramid
    public void nextLevel(){
        level+=1;
    }
    
    //which level of the pyramid the robot is on
    public int getLevel(){
        return level;
    }
    
    //resets level to zero
    public void resetLevel(){
        level=0;
    }
    
    //moves elevator to starting position and sets encoder
    public void homingSequence() {
        if (homeUp){
            while (!getUpperLimit()){
                climberMotor.set(homingSpeed);
            }
            while (getUpperLimit()){
                climberMotor.set(-homingReverseSpeed);
            }
            climberEncoder.reset();
        }
        else{
            while (!getLowerLimit()){
                climberMotor.set(-homingSpeed);
            }
            while (getLowerLimit()){
                climberMotor.set(homingReverseSpeed);
            }
            climberEncoder.reset();
        }
    }
    
    //whether hooks have attached
    public boolean getError(boolean goingUp){
        if (goingUp){
            return(!rightFixedHookMetalSensor.get()||!leftFixedHookMetalSensor.get());
        }
        else {
            return (!rightMovingHookMetalSensor.get()||!leftMovingHookMetalSensor.get());
        }
    }
}
