// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc100.Robot2013.subsystems;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
import org.usfirst.frc100.Robot2013.RobotMap;
/**
 *
 */
public class DriveTrain extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    Encoder leftEncoder = RobotMap.driveTrainLeftEncoder;
    Encoder rightEncoder = RobotMap.driveTrainRightEncoder;
    Accelerometer accelerometer = RobotMap.driveTrainAccelerometer;
    Gyro gyro = RobotMap.driveTrainGyro;
    DoubleSolenoid leftShifter = RobotMap.driveTrainLeftShifter;
    DoubleSolenoid rightShifter = RobotMap.driveTrainRightShifter;
    SpeedController left = RobotMap.driveTrainLeft;
    SpeedController right = RobotMap.driveTrainRight;
    RobotDrive robotDrive = RobotMap.driveTrainRobotDrive;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    double desiredHeading = 0.0;
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    public void tankDrive(double l, double r) {
        if (Math.abs(l) >= 0.95 && Math.abs(r) >= 0.95) {
            driveStraight( (int) (l / Math.abs(l)), gyro.getAngle());
        } else {
            left.set(l);
            right.set(r);
        }
    }
    
    public void arcadedrive(double y, double x){
        robotDrive.arcadeDrive(y, x);
    }
    
    public void driveStraight(int i, double heading) {
        desiredHeading = convertAngle((int)heading);
        left.set(.8 * i);
        right.set((.8 * i) + (convertAngle((int)gyro.getAngle()) - desiredHeading));
    }
    
    public void turn90(int i) {
        int heading = convertAngle((int)desiredHeading + (90 * i));
        left.set((convertAngle((int)gyro.getAngle()) - heading) / -90.0);
        right.set((convertAngle((int)gyro.getAngle()) - heading) / 90.0);
    }
    
    public int convertAngle(int i) {
        int modifiedHeading;
        if (i > 180) {
            modifiedHeading = -(360 - i);
        } else {
            modifiedHeading = i;
        }
        return modifiedHeading;
    }
    
    public void setHeading(int angle) {
        desiredHeading = angle;
    }
    
    public void resetSensors() {
        leftEncoder.reset();
        rightEncoder.reset();
        gyro.reset(); 
    }
    
    public void startSensors() {
        leftEncoder.start();
        rightEncoder.start();
    }
    
    public Gyro getGyro() {
        return gyro;
    }
    
    public void shiftUp() {
        leftShifter.set(DoubleSolenoid.Value.kForward);
        rightShifter.set(DoubleSolenoid.Value.kForward);
    }
    
    public void shiftDown() {
        leftShifter.set(DoubleSolenoid.Value.kReverse);
        rightShifter.set(DoubleSolenoid.Value.kReverse);
    }
}
