// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc100.Climber.subsystems;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
import org.usfirst.frc100.Climber.Robot;
import org.usfirst.frc100.Climber.RobotMap;
/**
 *
 */
public class Elevator extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    DigitalInput elevatorTopLimit = RobotMap.ElevatorTopLimit;
    DigitalInput elevatorBottomLimit = RobotMap.ElevatorBottomLimit;
    DigitalInput elevatorTiltLimit = RobotMap.ElevatorTiltLimit;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    public void raiseElevator(){
        
    }
    
    public void lowerElevator(){
        
    }
    
    public void tiltElevatorForward(){
        
    }
    
    public boolean getLowerLimit(){
        return elevatorBottomLimit.get();
        //return Robot.oi.lower.get();
    }
    
    public boolean getUpperLimit(){
        return elevatorTopLimit.get();
        //return Robot.oi.upper.get();
    }

    public boolean getTiltLimit() {
        return elevatorTiltLimit.get();
    }
}
