package org.usfirst.frc100.Robot2014.subsystems;

import org.usfirst.frc100.Robot2014.RobotMap;
import org.usfirst.frc100.Robot2014.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.PIDSource.PIDSourceParameter;
import edu.wpi.first.wpilibj.command.Subsystem;

/**
 * Controls the drive motors and shifters, and reads numerous sensors.
 */
public class DriveTrain extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController driveLeftMotorMain = RobotMap.driveTrainDriveLeftMotorMain;
    SpeedController driveLeftMotorSlave = RobotMap.driveTrainDriveLeftMotorSlave;
    SpeedController driveRightMotorMain = RobotMap.driveTrainDriveRightMotorMain;
    SpeedController driveRightMotorSlave = RobotMap.driveTrainDriveRightMotorSlave;
    Encoder driveLeftEncoder = RobotMap.driveTrainDriveLeftEncoder;
    Encoder driveRightEncoder = RobotMap.driveTrainDriveRightEncoder;
    Gyro gyro = RobotMap.driveTrainGyro;
    AnalogChannel rangeFinder = RobotMap.driveTrainRangeFinder;
    Relay shifter = RobotMap.driveTrainShifter;
    AnalogChannel leftLineReader = RobotMap.driveTrainLeftLineReader;
    AnalogChannel rightLineReader = RobotMap.driveTrainRightLineReader;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
}
